# Generated by scripts/release.py (release-kit) from the v2026.9.0 release — do not edit.
class Genie < Formula
  desc "A command line shell for using LLMs tools in the command line"
  homepage "https://github.com/grahambrooks/genie"
  version "2026.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/genie/releases/download/v2026.9.0/genie-v2026.9.0-aarch64-apple-darwin.tar.gz"
      sha256 "a8c4aa3519a298526b115341134aeadac4e0b9e4cb41c5d3069b8b3787d6d76d"
    end
    on_intel do
      url "https://github.com/grahambrooks/genie/releases/download/v2026.9.0/genie-v2026.9.0-x86_64-apple-darwin.tar.gz"
      sha256 "2ac8d24968bb50d632dfd7cf4caf04506c8343a24d23f73381b3fc99e56089ab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/genie/releases/download/v2026.9.0/genie-v2026.9.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "57585507220d907bb1d5ca256704510f687d3aca51e97511cbb7973006cc9d50"
    end
    on_intel do
      url "https://github.com/grahambrooks/genie/releases/download/v2026.9.0/genie-v2026.9.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ab39e2caf3a46bec7a93ef1d2a5831f1a1c2f930c9dbfaa0eb6c1c0d64657e21"
    end
  end

  def install
    bin.install "genie"
  end

  test do
    assert_path_exists bin/"genie"
  end
end
