# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Genie < Formula
  desc "A command line shell for using LLMs tools in the command line"
  homepage "https://github.com/grahambrooks/genie"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/genie/releases/download/v2026.10.1/genie-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "6d973c8c61f44424307e8ac0c26921e42af5f58a7410b8f486e518d5c1dd55f0"
    end
    on_intel do
      url "https://github.com/grahambrooks/genie/releases/download/v2026.10.1/genie-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "33bc718ec6444929e91a622fb2573a8fc9258fa7dc0b22de60124e2fe3d78f0b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/genie/releases/download/v2026.10.1/genie-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b68321b41fb8ad03e10dd5407c01b6c6f187f650ee43c7569f3e022f03a629c8"
    end
    on_intel do
      url "https://github.com/grahambrooks/genie/releases/download/v2026.10.1/genie-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "42ffed173f212557a012aff9d68d9dca0f024fa9b926919200e8e89aaa06da77"
    end
  end

  def install
    bin.install "genie"
  end

  test do
    assert_path_exists bin/"genie"
  end
end
